# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0011_auto_20170808_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('stripesource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djstripe.StripeSource')),
                ('account_holder_name', djstripe.fields.StripeCharField(help_text='The name of the person or business that owns the bank account.', max_length=5000, null=True)),
                ('account_holder_type', djstripe.fields.StripeCharField(choices=[('company', 'Company'), ('individual', 'Individual')], help_text='The type of entity that holds the account.', max_length=10)),
                ('bank_name', djstripe.fields.StripeCharField(help_text='Name of the bank associated with the routing number (e.g., `WELLS FARGO`).', max_length=255)),
                ('country', djstripe.fields.StripeCharField(help_text='Two-letter ISO code representing the country the bank account is located in.', max_length=2)),
                ('currency', djstripe.fields.StripeCharField(help_text='Three-letter ISO currency code', max_length=3)),
                ('default_for_currency', djstripe.fields.StripeNullBooleanField(default=None, help_text='Whether this external account is the default account for its currency.')),
                ('fingerprint', djstripe.fields.StripeCharField(help_text='Uniquely identifies this particular bank account. You can use this attribute to check whether two bank accounts are the same.', max_length=16)),
                ('last4', djstripe.fields.StripeCharField(max_length=4)),
                ('routing_number', djstripe.fields.StripeCharField(help_text='The routing transit number for the bank account.', max_length=255)),
                ('status', djstripe.fields.StripeCharField(choices=[('errored', 'Errored'), ('new', 'New'), ('validated', 'Validated'), ('verification_failed', 'Verification failed'), ('verified', 'Verified')], max_length=19)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('djstripe.stripesource',),
        ),
    ]
